name: auto-mod-fxn-v8
env:    
  TZ: America/Sanfransisco  
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        wget -q -O "file" https://www.bing.com/th?id=OHR.QuayBridge_EN-CA2917632382_1920x1080.jpg&rf=LaDigue_1920x1080.jpg
        mv file ./upload/
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%Y年%m月%d日%H时)"
    - name: Upload nightly release
      uses: svenstaro/upload-release-action@v2
      with:           
        repo_token: ${{ secrets.ACTION_TOKEN }}
        file: ./upload/file
        tag: ${{ github.ref }}           
        body: "Nightly build"           
        file_glob: true           
        prerelease: true           
        overwrite: true
    - uses: actions/upload-artifact@v2
      with:
          name: file
          path: ./upload/
